const START_QUIZ_SAGA = 'START_QUIZ_SAGA';
const ANSWER_QUESTION_SAGA = 'ANSWER_QUESTION_SAGA';
const SET_QUIZ_TIME = 'SET_QUIZ_TIME';
const TICK = 'TICK';
const GET_QUESTIONS = 'GET_QUESTIONS';
const SET_QUESTIONS = 'SET_QUESTIONS';
const INIT_PRIORITY_QUEUE = 'INIT_PRIORITY_QUEUE';
const POP_NEXT_KEY = 'POP_NEXT_KEY';
const INCREMENT_NUM_CORRECT = 'INCREMENT_NUM_CORRECT';
const INCREMENT_NUM_WRONG = 'INCREMENT_NUM_WRONG';
const START_TIMER_SAGA = 'START_TIMER_SAGA';
const DECREASE_QUESTION_TIME = 'DECREASE_QUESTION_TIME';
const LEVEL_UP_QUESTION = 'LEVEL_UP_QUESTION';
const GRADUATE_QUESTION = 'GRADUATE_QUESTION';
const GRADUATE_QUESTION_CAUTIOUSLY = 'GRADUATE_QUESTION_CAUTIOUSLY';
const REINSERT_QUESTION = 'REINSERT_QUESTION';
const INCREASE_GRADUATED_INTERVAL = 'INCREASE_GRADUATED_INTERVAL';
const RESET_QUESTION_LEVEL = 'RESET_QUESTION_LEVEL';
const NUM_QUESTIONS = 20;

export {
  START_QUIZ_SAGA,
  ANSWER_QUESTION_SAGA,
  SET_QUIZ_TIME,
  TICK,
  GET_QUESTIONS,
  SET_QUESTIONS,
  INIT_PRIORITY_QUEUE,
  NUM_QUESTIONS,
  POP_NEXT_KEY,
  INCREMENT_NUM_CORRECT,
  INCREMENT_NUM_WRONG,
  START_TIMER_SAGA,
  DECREASE_QUESTION_TIME,
  LEVEL_UP_QUESTION,
  GRADUATE_QUESTION,
  GRADUATE_QUESTION_CAUTIOUSLY,
  REINSERT_QUESTION,
  INCREASE_GRADUATED_INTERVAL,
  RESET_QUESTION_LEVEL,
};
