const START_QUIZ_SAGA = 'START_QUIZ_SAGA';
const SET_QUIZ_TIME = 'SET_QUIZ_TIME';
const GET_QUESTIONS = 'GET_QUESTIONS';
const SET_QUESTIONS = 'SET_QUESTIONS';

export { START_QUIZ_SAGA, SET_QUIZ_TIME, GET_QUESTIONS, SET_QUESTIONS };
