const START_QUIZ_SAGA = 'START_QUIZ_SAGA';
const ANSWER_QUESTION_SAGA = 'ANSWER_QUESTION_SAGA';
const SET_QUIZ_TIME = 'SET_QUIZ_TIME';
const TICK = 'TICK';
const GET_QUESTIONS = 'GET_QUESTIONS';
const SET_QUESTIONS = 'SET_QUESTIONS';
const INIT_PRIORITY_QUEUE = 'INIT_PRIORITY_QUEUE';
const POP_NEXT_KEY = 'POP_NEXT_KEY';
const ANSWERED_CORRECTLY = 'ANSWERED_CORRECTLY';
const ANSWERED_INCORRECTLY = 'ANSWERED_INCORRECTLY';
const START_TIMER_SAGA = 'START_TIMER_SAGA';
const DECREASE_QUESTION_TIME = 'DECREASE_QUESTION_TIME';
const NUM_QUESTIONS = 20;

export {
  START_QUIZ_SAGA,
  ANSWER_QUESTION_SAGA,
  SET_QUIZ_TIME,
  TICK,
  GET_QUESTIONS,
  SET_QUESTIONS,
  INIT_PRIORITY_QUEUE,
  NUM_QUESTIONS,
  POP_NEXT_KEY,
  ANSWERED_CORRECTLY,
  ANSWERED_INCORRECTLY,
  START_TIMER_SAGA,
  DECREASE_QUESTION_TIME,
};
